#!/usr/bin/env python3
"""Write every scene's drivable-base twin: scenes/<name>_mobile.xml, the scene with model/robot_mobile.xml attached
instead of model/robot.xml (see model/mobile_base.py). Run it after adding or changing a scene; the tests fail while a
twin is missing or out of date.

  python3 scenes/build_mobile.py

play.py and render_video.py load a scene's twin with --mobile-base. Twins whose scene is gone are deleted.
"""
import sys
from pathlib import Path

SCENES = Path(__file__).resolve().parent
sys.path.insert(0, str(SCENES.parent / "model"))
from mobile_base import drivable_variant  # noqa: E402

ROBOT, MOBILE_ROBOT = 'file="../model/robot.xml"', 'file="../model/robot_mobile.xml"'


def sources() -> list[Path]:
    """The scenes written by hand: every scenes/*.xml that is not a twin."""
    return [path for path in sorted(SCENES.glob("*.xml")) if drivable_variant(path) != path]


def twin(source: Path) -> str:
    """The text of a scene's twin. The scene's model name must be its file name."""
    text = source.read_text(encoding="utf-8")
    header = f'<mujoco model="{source.stem}">'
    for old in (header, ROBOT):
        if text.count(old) != 1:
            raise ValueError(f"{source.name} must contain {old} exactly once")
    text = text.replace(header, f'<mujoco model="{drivable_variant(source).stem}">').replace(ROBOT, MOBILE_ROBOT)
    return text.replace("\n", f"\n  <!-- Generated by scenes/build_mobile.py from {source.name}; do not edit. -->\n", 1)


def main() -> None:
    wanted = set()
    for source in sources():
        target = drivable_variant(source)
        target.write_text(twin(source), encoding="utf-8")
        wanted.add(target)
        print(f"wrote scenes/{target.name}")
    for stale in set(SCENES.glob("*.xml")) - set(sources()) - wanted:
        stale.unlink()
        print(f"deleted scenes/{stale.name}: its scene is gone")


if __name__ == "__main__":
    main()
